namespace DataFetcher;
public class Office
{
    public string Name {get;set;}
}

public class Region
{
    public string Name {get;set;}
    public List<Office> Offices {get; set;}

    public static List<Region> GetRegions()
    {
        return new List<Region>()
        {
            new Region() { Name = "Central Office", Offices = new List<Office>() {
                    new Office() {Name="Buildings and Special Projects Management Cluster"},
                    new Office() {Name="Bureau of Construction"},
                    new Office() {Name="Bureau of Maintenance"},
                    new Office() {Name="Bureau of Quality and Safety"},
                    new Office() {Name="Flood Control Management Cluster"},
                    new Office() {Name="Regional Project Management Office - Bangsamoro Autonomous Region in Muslim Mindanao"},
                    new Office() {Name="Roads Management Cluster I (Bilateral)"},
                    new Office() {Name="Roads Management Cluster II (Multilateral)"},
                }
            },
            new Region() { Name = "Cordillera Administrative Region", Offices = new List<Office>() {
                    new Office() {Name="Abra District Engineering Office"},
                    new Office() {Name="Apayao 1st District Engineering Office"},
                    new Office() {Name="Apayao 2nd District Engineering Office"},
                    new Office() {Name="Baguio City District Engineering Office"},
                    new Office() {Name="Benguet 1st District Engineering Office"},
                    new Office() {Name="Benguet 2nd District Engineering Office"},
                    new Office() {Name="Cordillera Administrative Region"},
                    new Office() {Name="Ifugao 1st District Engineering Office"},
                    new Office() {Name="Ifugao 2nd District Engineering Office"},
                    new Office() {Name="Lower Kalinga District Engineering Office"},
                    new Office() {Name="Mountain Province 1st District Engineering Office"},
                    new Office() {Name="Mountain Province 2nd District Engineering Office"},
                    new Office() {Name="Upper Kalinga District Engineering Office"},
                }
            },
            new Region() { Name = "National Capital Region", Offices = new List<Office>() {
                    new Office() {Name="Las Piñas-Muntinlupa District Engineering Office"},
                    new Office() {Name="Malabon-Navotas District Engineering Office"},
                    new Office() {Name="Metro Manila 1st District Engineering Office"},
                    new Office() {Name="Metro Manila 2nd District Engineering Office"},
                    new Office() {Name="Metro Manila 3rd District Engineering Office"},
                    new Office() {Name="National Capital Region"},
                    new Office() {Name="North Manila District Engineering Office"},
                    new Office() {Name="Quezon City 1st District Engineering Office"},
                    new Office() {Name="Quezon City 2nd District Engineering Office"},
                    new Office() {Name="South Manila District Engineering Office"},
                }
            },
            new Region() { Name = "Negros Island Region", Offices = new List<Office>() {
                    new Office() {Name="Negros Island Region"},
                }
            },
            new Region() { Name = "Region I", Offices = new List<Office>() {
                    new Office() {Name="Ilocos Norte 1st District Engineering Office"},
                    new Office() {Name="Ilocos Norte 2nd District Engineering Office"},
                    new Office() {Name="Ilocos Sur 1st District Engineering Office"},
                    new Office() {Name="Ilocos Sur 2nd District Engineering Office"},
                    new Office() {Name="La Union 1st District Engineering Office"},
                    new Office() {Name="La Union 2nd District Engineering Office"},
                    new Office() {Name="Pangasinan 1st District Engineering Office"},
                    new Office() {Name="Pangasinan 2nd District Engineering Office"},
                    new Office() {Name="Pangasinan 3rd District Engineering Office"},
                    new Office() {Name="Pangasinan 4th District Engineering Office"},
                    new Office() {Name="Region I"},
                }
            },
            new Region() { Name = "Region II", Offices = new List<Office>() {
                    new Office() {Name="Batanes District Engineering Office"},
                    new Office() {Name="Cagayan 1st District Engineering Office"},
                    new Office() {Name="Cagayan 2nd District Engineering Office"},
                    new Office() {Name="Cagayan 3rd District Engineering Office"},
                    new Office() {Name="Isabela 1st District Engineering Office"},
                    new Office() {Name="Isabela 2nd District Engineering Office"},
                    new Office() {Name="Isabela 3rd District Engineering Office"},
                    new Office() {Name="Isabela 4th District Engineering Office"},
                    new Office() {Name="Nueva Vizcaya 2nd District Engineering Office"},
                    new Office() {Name="Nueva Vizcaya District Engineering Office"},
                    new Office() {Name="Quirino District Engineering Office"},
                    new Office() {Name="Region II"},
                }
            },
            new Region() { Name = "Region III", Offices = new List<Office>() {
                    new Office() {Name="Aurora District Engineering Office"},
                    new Office() {Name="Bataan 1st District Engineering Office"},
                    new Office() {Name="Bataan 2nd District Engineering Office"},
                    new Office() {Name="Bataan 3rd District Engineering Office"},
                    new Office() {Name="Bulacan 1st District Engineering Office"},
                    new Office() {Name="Bulacan 2nd District Engineering Office"},
                    new Office() {Name="Bulacan 3rd District Engineering Office"},
                    new Office() {Name="Nueva Ecija 1st District Engineering Office"},
                    new Office() {Name="Pampanga 1st District Engineering Office"},
                    new Office() {Name="Pampanga 2nd District Engineering Office"},
                    new Office() {Name="Pampanga 3rd District Engineering Office"},
                    new Office() {Name="Region III"},
                    new Office() {Name="Tarlac 2nd District Engineering Office"},
                    new Office() {Name="Tarlac District Engineering Office"},
                    new Office() {Name="Zambales 1st District Engineering Office"},
                    new Office() {Name="Zambales 2nd District Engineering Office"},
                }
            },
            new Region() { Name = "Region IV-A", Offices = new List<Office>() {
                    new Office() {Name="Batangas 1st District Engineering Office"},
                    new Office() {Name="Batangas 2nd District Engineering Office"},
                    new Office() {Name="Batangas 3rd District Engineering Office"},
                    new Office() {Name="Batangas 4th District Engineering Office"},
                    new Office() {Name="Cavite 1st District Engineering Office"},
                    new Office() {Name="Cavite 2nd District Engineering Office"},
                    new Office() {Name="Cavite 3rd District Engineering Office"},
                    new Office() {Name="Laguna 1st District Engineering Office"},
                    new Office() {Name="Laguna 2nd District Engineering Office"},
                    new Office() {Name="Laguna 3rd District Engineering Office"},
                    new Office() {Name="Quezon 1st District Engineering Office"},
                    new Office() {Name="Quezon 2nd District Engineering Office"},
                    new Office() {Name="Quezon 3rd District Engineering Office"},
                    new Office() {Name="Quezon 4th District Engineering Office"},
                    new Office() {Name="Region IV-A"},
                    new Office() {Name="Rizal 1st District Engineering Office"},
                    new Office() {Name="Rizal 2nd District Engineering Office"},
                }
            },
            new Region() { Name = "Region IV-B", Offices = new List<Office>() {
                    new Office() {Name="Marinduque District Engineering Office"},
                    new Office() {Name="Mindoro Occidental District Engineering Office"},
                    new Office() {Name="Mindoro Oriental District Engineering Office"},
                    new Office() {Name="Palawan 1st District Engineering Office"},
                    new Office() {Name="Palawan 2nd District Engineering Office"},
                    new Office() {Name="Palawan 3rd District Engineering Office"},
                    new Office() {Name="Region IV-B"},
                    new Office() {Name="Romblon District Engineering Office"},
                    new Office() {Name="Southern Mindoro District Engineering Office"},
                }
            },
            new Region() { Name = "Region V", Offices = new List<Office>() {
                    new Office() {Name="Albay 1st District Engineering Office"},
                    new Office() {Name="Albay 2nd District Engineering Office"},
                    new Office() {Name="Albay 3rd District Engineering Office"},
                    new Office() {Name="Camarines Norte District Engineering Office"},
                    new Office() {Name="Camarines Norte Sub-District Engineering Office"},
                    new Office() {Name="Camarines Sur 1st District Engineering Office"},
                    new Office() {Name="Camarines Sur 2nd District Engineering Office"},
                    new Office() {Name="Camarines Sur 3rd District Engineering Office"},
                    new Office() {Name="Camarines Sur 4th District Engineering Office"},
                    new Office() {Name="Camarines Sur 5th District Engineering Office"},
                    new Office() {Name="Catanduanes District Engineering Office"},
                    new Office() {Name="Masbate 1st District Engineering Office"},
                    new Office() {Name="Masbate 2nd District Engineering Office"},
                    new Office() {Name="Region V"},
                    new Office() {Name="Sorsogon 2nd District Engineering Office"},
                    new Office() {Name="Sorsogon District Engineering Office"},
                }
            },
            new Region() { Name = "Region VI", Offices = new List<Office>() {
                    new Office() {Name="Aklan District Engineering Office"},
                    new Office() {Name="Antique District Engineering Office"},
                    new Office() {Name="Bacolod City District Engineering Office"},
                    new Office() {Name="Capiz 1st District Engineering Office"},
                    new Office() {Name="Capiz 2nd District Engineering Office"},
                    new Office() {Name="Guimaras District Engineering Office"},
                    new Office() {Name="Iloilo 1st District Engineering Office"},
                    new Office() {Name="Iloilo 2nd District Engineering Office"},
                    new Office() {Name="Iloilo 3rd District Engineering Office"},
                    new Office() {Name="Iloilo 4th District Engineering Office"},
                    new Office() {Name="Iloilo 6th District Engineering Office"},
                    new Office() {Name="Iloilo City District Engineering Office"},
                    new Office() {Name="Negros Occidental 1st District Engineering Office"},
                    new Office() {Name="Negros Occidental 2nd District Engineering Office"},
                    new Office() {Name="Negros Occidental 3rd District Engineering Office"},
                    new Office() {Name="Negros Occidental 4th District Engineering Office"},
                    new Office() {Name="Negros Occidental 5th District Engineering Office"},
                    new Office() {Name="Region VI"},
                }
            },
            new Region() { Name = "Region VII", Offices = new List<Office>() {
                    new Office() {Name="Bohol 1st District Engineering Office"},
                    new Office() {Name="Bohol 2nd District Engineering Office"},
                    new Office() {Name="Bohol 3rd District Engineering Office"},
                    new Office() {Name="Cebu 1st District Engineering Office"},
                    new Office() {Name="Cebu 2nd District Engineering Office"},
                    new Office() {Name="Cebu 3rd District Engineering Office"},
                    new Office() {Name="Cebu 4th District Engineering Office"},
                    new Office() {Name="Cebu 5th District Engineering Office"},
                    new Office() {Name="Cebu 6th District Engineering Office"},
                    new Office() {Name="Cebu 7th District Engineering Office"},
                    new Office() {Name="Cebu City District Engineering Office"},
                    new Office() {Name="Negros Oriental 1st District Engineering Office"},
                    new Office() {Name="Negros Oriental 2nd District Engineering Office"},
                    new Office() {Name="Negros Oriental 3rd District Engineering Office"},
                    new Office() {Name="Region VII"},
                    new Office() {Name="Siquijor District Engineering Office"},
                }
            },
            new Region() { Name = "Region VIII", Offices = new List<Office>() {
                    new Office() {Name="Biliran District Engineering Office"},
                    new Office() {Name="Eastern Samar District Engineering Office"},
                    new Office() {Name="Leyte 1st District Engineering Office"},
                    new Office() {Name="Leyte 2nd District Engineering Office"},
                    new Office() {Name="Leyte 3rd District Engineering Office"},
                    new Office() {Name="Leyte 4th District Engineering Office"},
                    new Office() {Name="Leyte 5th District Engineering Office"},
                    new Office() {Name="Northern Samar 1st District Engineering Office"},
                    new Office() {Name="Northern Samar 2nd District Engineering Office"},
                    new Office() {Name="Region VIII"},
                    new Office() {Name="Samar 1st District Engineering Office"},
                    new Office() {Name="Samar 2nd District Engineering Office"},
                    new Office() {Name="Southern Leyte 1st District Engineering Office"},
                    new Office() {Name="Southern Leyte 2nd District Engineering Office"},
                    new Office() {Name="Tacloban City District Engineering Office"},
                }
            },
            new Region() { Name = "Region IX", Offices = new List<Office>() {
                    new Office() {Name="Isabela City District Engineering Office"},
                    new Office() {Name="Region IX"},
                    new Office() {Name="Zamboanga City 1st District Engineering Office"},
                    new Office() {Name="Zamboanga City 2nd District Engineering Office"},
                    new Office() {Name="Zamboanga del Norte 1st District Engineering Office"},
                    new Office() {Name="Zamboanga del Norte 2nd District Engineering Office"},
                    new Office() {Name="Zamboanga del Norte 3rd District Engineering Office"},
                    new Office() {Name="Zamboanga del Norte 4th District Engineering Office"},
                    new Office() {Name="Zamboanga del Sur 1st District Engineering Office"},
                    new Office() {Name="Zamboanga del Sur 2nd District Engineering Office"},
                    new Office() {Name="Zamboanga Sibugay 1st District Engineering Office"},
                    new Office() {Name="Zamboanga Sibugay 2nd District Engineering Office"},
                }
            },
                    new Region() { Name = "Region X", Offices = new List<Office>() {
                    new Office() {Name="Bukidnon 1st District Engineering Office"},
                    new Office() {Name="Bukidnon 2nd District Engineering Office"},
                    new Office() {Name="Bukidnon 3rd District Engineering Office"},
                    new Office() {Name="Bukidnon 4th District Engineering Office"},
                    new Office() {Name="Cagayan de Oro City 1st District Engineering Office"},
                    new Office() {Name="Cagayan de Oro City 2nd District Engineering Office"},
                    new Office() {Name="Camiguin District Engineering Office"},
                    new Office() {Name="Iligan City District Engineering Office"},
                    new Office() {Name="Lanao del Norte 1st District Engineering Office"},
                    new Office() {Name="Lanao del Norte 2nd District Engineering Office"},
                    new Office() {Name="Misamis Occidental 1st District Engineering Office"},
                    new Office() {Name="Misamis Occidental 2nd District Engineering Office"},
                    new Office() {Name="Misamis Oriental 1st District Engineering Office"},
                    new Office() {Name="Misamis Oriental 2nd District Engineering Office"},
                    new Office() {Name="Region X"},
                }
            },
            new Region() { Name = "Region XI", Offices = new List<Office>() {
                    new Office() {Name="Davao City 2nd District Engineering Office"},
                    new Office() {Name="Davao City 3rd District Engineering Office"},
                    new Office() {Name="Davao City District Engineering Office"},
                    new Office() {Name="Davao de Oro 1st District Engineering Office"},
                    new Office() {Name="Davao de Oro 2nd District Engineering Office"},
                    new Office() {Name="Davao del Norte 2nd District Engineering Office"},
                    new Office() {Name="Davao del Norte District Engineering Office"},
                    new Office() {Name="Davao del Sur District Engineering Office"},
                    new Office() {Name="Davao Occidental District Engineering Office"},
                    new Office() {Name="Davao Oriental 1st District Engineering Office"},
                    new Office() {Name="Davao Oriental 2nd District Engineering Office"},
                    new Office() {Name="Region XI"},
                }
            },
            new Region() { Name = "Region XII", Offices = new List<Office>() {
                    new Office() {Name="Cotabato 1st District Engineering Office"},
                    new Office() {Name="Cotabato 2nd District Engineering Office"},
                    new Office() {Name="Cotabato 3rd District Engineering Office"},
                    new Office() {Name="Region XII"},
                    new Office() {Name="Sarangani District Engineering Office"},
                    new Office() {Name="South Cotabato 1st District Engineering Office  "},
                    new Office() {Name="South Cotabato 2nd District Engineering Office"},
                    new Office() {Name="Sultan Kudarat 1st District Engineering Office"},
                    new Office() {Name="Sultan Kudarat 2nd District Engineering Office"},
                }
            },
            new Region() { Name = "Region XIII", Offices = new List<Office>() {
                    new Office() {Name="Agusan del Norte District Engineering Office"},
                    new Office() {Name="Agusan del Sur 1st District Engineering Office"},
                    new Office() {Name="Agusan del Sur 2nd District Engineering Office"},
                    new Office() {Name="Butuan City District Engineering Office"},
                    new Office() {Name="Dinagat Islands District Engineering Office"},
                    new Office() {Name="Region XIII"},
                    new Office() {Name="Surigao del Norte 1st District Engineering Office"},
                    new Office() {Name="Surigao del Norte 2nd District Engineering Office"},
                    new Office() {Name="Surigao del Sur 1st District Engineering Office"},
                    new Office() {Name="Surigao del Sur 2nd District Engineering Office"},
                }
            },
        };
    }

}