export const regionsList:string[] = new Array(
    "Central Office",
    "Cordillera Administrative Region",
    "National Capital Region",
    "Negros Island Region",
    "Region I",
    "Region II",
    "Region III",
    "Region IV-A",
    "Region IV-B",
    "Region V",
    "Region VI",
    "Region VII",
    "Region VIII",
    "Region IX",
    "Region X",
    "Region XI",
    "Region XII",
    "Region XIII"
)