using Categorizer;

Console.WriteLine($"[{DateTime.Now:HH:mm:ss.fff}] Categorizer Start");
ProjectCategorizer c = new ProjectCategorizer();
c.LoadData("Data/MasterData.json", "Data/AllContracts.json");
//c.TestCategorize("ORGANIZATIONAL OUTCOME 1: ENSURE SAFE AND RELIABLE NATIONAL ROAD SYSTEM: NETWORK DEVELOPMENT: CONSTRUCTION OF BY-PASS ROAD, PACKAGE 2, ISABELA (GOV. DY BRIDGE)");
//c.TestCategorize("CONVERGENCE AND SPECIAL SUPPORT PROGRAM-CONSTRUCTION/IMPROVEMENT OF VARIOUS INFRASTRUCTURES IN SUPPORT OF NATIONAL SECURITY (TATAG NG IMPRASTRAKTURA PARA SA KAPAYAPAAN AT SEGURIDAD PROGRAM-TIKAS)- CONSTRUCTION OF BARRACKS, ISAFP, CAMP LAPU-LAPU, APAS");
//c.TestCategorize("CONVERGENCE AND SPECIAL SUPPORT PROGRAM - SPECIAL ROAD FUND - MOTOR VEHICLE USERS CHARGE (MVUC) - AS PER R.A. 11239, CONSTRUCTION AND INSTALLATION OF SOLAR STREETLIGHTS, SAFETY SIGNS AND DEVICES - K0065+000 - K0072+000, ARGAO, CEBU");
Console.WriteLine($"[{DateTime.Now:HH:mm:ss.fff}] Categorizer Finished");
